### ISSUE TITLE
Heading - Candidate NLDS - A11y getest

### ISSUE THREAD

**Issue by rianrietveld** [nl-design-system/candidate#167]
## Review toegankelijkheid voor de NLDS Candidate component Heading

Acceptatiecriteria: [NL Design System Acceptatiecriteria voor Heading](https://nldesignsystem.nl/heading)

### Hoe te testen

Ga naar de te reviewen component in StoryBook.
- Bij de component, kies in de zijbalk de view Documentatie.
- Review elke story van de component
- Bij een story staat er echtsboben een knop "Open canvas in new tab".
- Deze tab geeft je de mogelijkheid de component geïsoleerd te testen.

## Review toegankelijkheid op 17 december door Rian Rietveld

Gereviewed: https://candidate-storybook-test.vercel.app/?path=/docs/componenten-heading--documentatie
Met de stories
- Heading 1
- Heading 2 in een koppenstructuur
- Heading 3 in een koppenstructuur
- Heading 4 in een koppenstructuur
- Heading 5 in een koppenstructuur
- Heading 6 in een koppenstructuur
- 1e story: Heading 1 met meerdere regels tekst
- 2e story: Heading 1 met meerdere regels tekst
- Heading met Arabisch schrift in een Nederlandstalige pagina
- Heading lettertypes en kleuren
- Heading met visueel design voor lettergrootte en line-height per heading level

#### De koptekst maakt duidelijk waar de sectie over gaat
WCAG [2.4.6 Koppen en labels](https://nldesignsystem.nl/wcag/2.4.6)
Oordeel: voldoet.
**Update 19 december'24** isses met onderstaande stories zijn opgelost.

Review 17 december '24:
Oordeel: voldoet gedeeltelijk.
- voldoet niet: "1e story: Heading 1 met meerdere regels tekst vol". Er is er geen inhoudelijke relatie en de tekst eronder.
- voldoet niet: "story "Heading met Arabisch schrift in een Nederlandstalige pagina". In de koppenlijst van een screen reader is het onduidelijk voor een Nederlandstalige gebruiker waar de sectie eronder over gaat onder het arabische kopje. Deze twee stories zijn geen goed voorbeeld omdat de inhoud van de heading niet (eenduidig voor alle gebruikers) beschrijft waar de inhoud eronder over gaat. 

De overige stories voldoen wel.

#### Elementen moeten genest zijn volgens de HTML-specificatie
WCAG [4.1.1 Parsen](https://nldesignsystem.nl/wcag/4.1.1), extra voor NLDS
Oordeel: voldoet.

#### De contrastverhouding van de tekstkleur met de achtergrondkleur is hoog genoeg
WCAG [1.4.3 Contrast (minimum)](https://nldesignsystem.nl/wcag/1.4.3)
Oordeel: voldoet.

#### Als je de tekst vergroot tot 200% blijft deze in zijn geheel zichtbaar
WCAG [1.4.4 Herschalen van tekst](https://nldesignsystem.nl/wcag/1.4.4)
Oordeel: voldoet.

#### Als je de tekstafstand vergroot blijft de tekst in zijn geheel zichtbaar
WCAG [1.4.12 Tekstafstand](https://nldesignsystem.nl/wcag/1.4.12)
Oordeel: voldoet.

#### Als tekst er uitziet als een kop, moet dit ook in de HTML een kop zijn en geen vet gemaakte tekst
WCAG [1.3.1 Info en relaties](https://nldesignsystem.nl/wcag/1.3.1)
Oordeel: voldoet.

**Comment by Robbert** [comment]
@rianrietveld Er is wel een relatie bij die 1e story, omdat het de titel is van het album waar de muziek over gaat, zie: https://en.wikipedia.org/wiki/When_the_Pawn...

**Comment by Robbert** [comment]
@rianrietveld ik heb beide 2.4.6 issues verbeterd: https://github.com/nl-design-system/candidate/pull/399

**Comment by rianrietveld** [comment]
@Robbert ik vind het nog niet goed.
https://candidate-storybook-test.vercel.app/?path=/story/componenten-heading--heading-arabic
Bij` <h2 class="nl-heading nl-heading--level-2" dir="rtl" lang="ar">عيد الفطر (Suikerfeest)</h2>` is een deel in het arabisch en een deel in het Nederlands.
Hier zou je dit moeten doen:
` ``
<h2 class="nl-heading nl-heading--level-2" dir="rtl">
<span  lang="ar">رعيد الفط</span> (Suikerfeest)
</h2>```

Over de lange heading, eerste story: Inside jokes qua muziek lijkt me niet de plek hier. Het is een hele slechte titel, ik kan dit niet goed lezen, wat een muur van zwart. Qau gebruikersvriendelijkheid en leesbaarheid is this the hell.
Ik vind het hele voorbeeld verwarrend en zou het helemaal weghalen.

**Comment by rianrietveld** [comment]
Issues opgelost in PR https://github.com/nl-design-system/candidate/pull/405

Status A11y getest gezet in:
https://github.com/orgs/nl-design-system/projects/32/views/3
