### ISSUE TITLE
Color Sample - Community Utrecht - A11y getest

### ISSUE THREAD

**Issue by rianrietveld** [nl-design-system/candidate#196]
## Review toegankelijkheid voor de Color Sample component in Community bij Utrecht

- Te reviewen: [Color Sample in StoryBook Utrecht](https://nl-design-system.github.io/utrecht/storybook/?path=/docs/css_css-color-sample--docs)
- Acceptatiecriteria: [NL Design System Acceptatiecriteria voor Color Sample](https://nldesignsystem.nl/color-sample)

Note: Amsterdam heeft geen Community component voor Color Sample.

### Hoe te testen

Ga naar de te reviewen component in StoryBook
- Bij de component, kies in de zijbalk de view Default
- Klik op het open nieuwe tab icon rechtsboven in de taakbalk.
- Je ziet nu alleen de component met de bijbehorende CSS.

## Review toegankelijkheid door Marjon op 21 november 2024

Gereviewd: [Default Color Sample in StoryBook Utrecht](https://nl-design-system.github.io/utrecht/storybook-css/iframe.html?args=&id=css-color-sample--default&viewMode=story)

HTML basisvoorbeeld:

```html
<data class="utrecht-color-sample" style="color: rgb(0, 125, 173);" value="#007DAD"></data>
```

### Acceptatiecriteria

**Samenvatting:** de Color Sample component in Community bij Utrecht **voldoet niet** aan de acceptatiecriteria voor toegankelijkheid van het NL Design System.

#### Toegankelijkheid algemeen

- [x] De eigenschappen van de Color Sample staan in tekst
WCAG [1.4.5 Afbeeldingen van tekst](https://www.nldesignsystem.nl/wcag/1.4.5)
Oordeel: Niet van toepassing, er is geen tekst.

#### Toegankelijkheid visueel ontwerp

- [x] Het kleurcontrast van de tekst van de eigenschappen van de Color Sample is voldoende
[1.4.3 Contrast (minimum)](https://www.nldesignsystem.nl/wcag/1.4.3)
Oordeel: Niet van toepassing, er is geen tekst.
- [x] Het kleurvlak is duidelijk te onderscheiden ten opzichte van de achtergrond
WCAG [1.4.11 Contrast van niet-tekstuele content](https://www.nldesignsystem.nl/wcag/1.4.11)
Oordeel: Voldoet. De gebruikte kleur `rgb(0, 125, 173)` heeft een contrast van 4,6:1 op de witte achtergrond.

#### Toegankelijkheid zoom en herschalen

- [x] Als je de tekst vergroot tot 200% blijft deze in zijn geheel zichtbaar
WCAG [1.4.4 Herschalen van tekst](https://www.nldesignsystem.nl/wcag/1.4.4)
Oordeel: Niet van toepassing, er is geen tekst.
- [x] Als je de tekstafstand vergroot blijft de tekst in zijn geheel zichtbaar
WCAG [1.4.12 Tekstafstand](https://www.nldesignsystem.nl/wcag/1.4.12)
Oordeel: Niet van toepassing, er is geen tekst.

#### Toegankelijkheid screenreader

- [ ] De eigenschappen van de kleur in de Color Sample zijn in tekst beschreven
WCAG [1.1.1 Niet-tekstuele content](https://www.nldesignsystem.nl/wcag/1.1.1)
Oordeel: Voldoet niet. Er is alleen een gekleurd vierkant te zien, zonder tekst.
- [x] Het kleurvlak en de bijbehorende eigenschappen horen semantisch bij elkaar
WCAG [1.3.1 Info en relaties](https://www.nldesignsystem.nl/wcag/1.3.1)
Oordeel: Niet van toepassing, er zijn geen bijbehorende eigenschappen.
- [x] Een screenreadergebruiker kan uit de leesvolgorde herkennen welk kleurvlak bij welke eigenschappen hoort
WCAG [1.3.2 Betekenisvolle volgorde](https://www.nldesignsystem.nl/wcag/1.3.2)
Oordeel: Niet van toepassing, er zijn geen bijbehorende eigenschappen.

**Comment by MarjonBakker** [comment]
Er is geen tekstalternatief. Daardoor zijn een aantal richtlijnen niet van toepassing. Zodra een tekstalternatief toegevoegd is, moeten we de component ook testen op de overige criteria.

cc @jeffreylauwers @matijs
