### ISSUE TITLE
Code Block - Candidate NLDS - A11y getest

### ISSUE THREAD

**Issue by rianrietveld** [nl-design-system/candidate#207]
## Review toegankelijkheid voor de NLDS Candidate component Code Block

Acceptatiecriteria: [NL Design System Acceptatiecriteria voor Code Block](https://nldesignsystem.nl/code-block)

Hoe te testen

Ga naar de te reviewen component in StoryBook.

- Bij de component, kies in de zijbalk de view Documentatie.
- Review elke story van de component
- Bij een story staat er echtsboben een knop "Open canvas in new tab".
- Deze tab geeft je de mogelijkheid de component geïsoleerd te testen.

## Review toegankelijkheid op 17 december door Rian Rietveld

Gereviewd: https://candidate-storybook-test.vercel.app/?path=/docs/componenten-code-block--documentatie

Met de stories:
- Code Block met 1 regel ECMAScript
- Code Block met 1 kort Unix shell commando
- Code Block met 1 extra lange regel
- Code Block waar geen design token voor font-family is ingesteld
- Code Block met fallback font-family
- Code met Nederlandse taal
- Code met Engelse taal
- Code Block in Engelse taal geplaatst binnen Arabische rechts-naar-links pagina

#### De tekst, gemarkeerd als code, is niet alleen herkenbaar aan een andere achtergrondkleur
WCAG [1.4.1 Gebruik van kleur](https://nldesignsystem.nl/wcag/1.4.1)
Oordeel: voldoet.

#### De tekst, gemarkeerd als code, heeft voldoende contrast met de achtergrondkleur
WCAG [1.4.3 Contrast (minimum)](https://nldesignsystem.nl/wcag/1.4.3)
Oordeel: voldoet.

#### Wanneer de achtergrondkleur van het Code Block anders is dan de default browserkleur, dan heeft deze een kleurcontrast van minimaal 3:1 met de achtergrondkleur van de pagina
WCAG [1.4.11 Contrast van niet-tekstuele content](https://nldesignsystem.nl/wcag/1.4.11)
Oordeel: niet getest, hier is geen story van.

#### Als je inzoomt naar 200% blijft alle tekst leesbaar
WCAG [1.4.4 Herschalen van tekst](https://nldesignsystem.nl/wcag/1.4.4)
Oordeel: Voldoet.
**Update 18 december '24**: de tabindex="0" is toegevoegd bij een blok met een scrollbar.
Review 17 december : Voldoet niet. Het code block kan geen toestenbordfocus ontvangen en de scrollbar is daarom niet te bedienen met een toestenbord. Dit is een probleem in Safari.
Oplossing: voeg tabindex="0" toe, eventueel alleen als er een scrollbar verschijnt. Matijs had hier een JavaScript oplossing voor.

#### Als je de tekstafstand vergroot blijft de tekst in zijn geheel zichtbaar
WCAG [1.4.12 Tekstafstand](https://nldesignsystem.nl/wcag/1.4.12)
Oordeel: Voldoet
**Update 18 december '24**: de tabindex="0" is toegevoegd bij een blok met een scrollbar.
Review 17 december : Voldoet niet. Het code block kan geen toestenbordfocus ontvangen en de scrollbar is daarom niet te bedienen met een toestenbord. Dit is een probleem in Safari.
Oplossing: voeg tabindex="0" toe, eventueel alleen als er een scrollbar verschijnt. Matijs had hier een JavaScript oplossing voor.

#### De juiste HTML-elementen voor de Code Block component zijn toegepast
WCAG [1.4.3 Contrast (minimum)](https://nldesignsystem.nl/wcag/1.4.3)
Oordeel: voldoet.

**Comment by Robbert** [comment]
@rianrietveld Ik heb het idee dat 1.4.11 hier niet van toepassing is vanuit WCAG, omdat een code block geen [user interface component](https://www.w3.org/TR/WCAG22/#dfn-user-interface-components) is. Als het om een Code Editor of een Textarea gaat, dan zou het wel van toepassing zijn.

**Comment by Robbert** [comment]
@rianrietveld waarom voldoet Tekstafstand niet? Bij mij werkte de bookmarklet van Steve Faulkner prima

<img width="642" alt="Code Block met extra text spacing" src="https://github.com/user-attachments/assets/5fe66ef7-3f52-4520-87c2-0a095c934b1d" />

**Comment by rianrietveld** [comment]
@Robbert 

> Ik heb het idee dat 1.4.11 hier niet van toepassing is vanuit WCAG, omdat een code block geen [user interface component](https://www.w3.org/TR/WCAG22/#dfn-user-interface-components) is. Als het om een Code Editor of een Textarea gaat, dan zou het wel van toepassing zijn.

Hier heeft kleur betekenis, het is een afkadering van het code blok.
Anyhow, als de acceptatiecriteria ter discussie wilt stellen, is dit niet de plek.
Het leidt in dit geval niet tot afkeureing, want we doen het niet, maar ik denk dat we het wel mee moeten nemen bij afwijkend ontwerp door anderen dan het kernteam.

Er komt geen scollbar als dat nodig zou moeten zijn, het gaat om de breedte van de tekst die anders is dan bij normale view. Tekst spacing an sich doet het wel, maar er komt geen tabindex="0" als de tekst een horizontale scrollbar veroorzaakt.
