### ISSUE TITLE
Number Badge - Candidate NLDS - A11y getest

### ISSUE THREAD

**Issue by rianrietveld** [nl-design-system/candidate#212]
## Review toegankelijkheid voor de NLDS Candidate component Number Badge

Acceptatiecriteria: [NL Design System Acceptatiecriteria voor Number Badge](https://nldesignsystem.nl/number-badge)

### Hoe te testen

Ga naar de te reviewen component in StoryBook.

- Bij de component, kies in de zijbalk de view Documentatie.
- Review elke story van de component
- Bij een story staat er echtsboben een knop "Open canvas in new tab".
-  Deze tab geeft je de mogelijkheid de component geïsoleerd te testen.

## Review toegankelijkheid op 17 december door Rian Rietveld

Gereviewd: https://candidate-storybook-test.vercel.app/?path=/docs/componenten-number-badge--documentatie
In deze Number Badge stories wordt het HTML element `<data>` gebruikt om een nummer weer te geven (behalve in de laatste story).

Met de stories
- Number Badge 
- Number Badge — miljoen
- Number Badge (nl-NL)
- Number Badge (en-GB)
- Number Badge in een flexbox (met links de tekst "Inbox" en rechts het getal "42")
- Number Badge in een flexbox (met boven de tekst "Inbox" en onder het getal "42")
- Number Badge in een smalle container
- Number Badge met een div HTML-element
- Number Badge text centreren
- Number Badge in tekst met grote letters
- Number Badge moet niet te klein worden
- Number Badge moet niet onderstreept zijn
- Number Badge moet een border kunnen hebben
- Number Badge moet er in forced colors mode uitzien als een link
- Number Badge moet niet de font-style overnemen van de parent

#### Gebruik geen afbeeldingen van tekst voor de Number Badge
WCAG [1.4.5 Afbeeldingen van tekst](https://nldesignsystem.nl/wcag/1.4.5)
Oordeel: voldoet.

#### Als een tekst en/of het aria-label in de Number Badge in een andere taal is dan de taal van de pagina, dan heeft de Number Badge een lang-attribuut met de juiste taalcode
WCAG [3.1.2 Taal van onderdelen](https://nldesignsystem.nl/wcag/3.1.2)
Oordeel: voldoet, alleen de story met de Duitse tekst voldoet conditioneel.

Of het Duitse cijfer goed wordt voorgelezen is afhankelijk van de screenreader en de beschikbare taal.
VoiceOver leest in het Duits de losse cijfers voor. Mijn NVDA heeft de Duitse taal niet en leest het cijfer in de taal van de pagina voor (Engels).

#### De tekst van de Number Badge heeft voldoende contrast tegen de achtergrond
WCAG [1.4.3 Contrast (minimum)](https://nldesignsystem.nl/wcag/1.4.3)
Oordeel: voldoet.

#### Als je de tekst van de Number Badge vergroot tot 200% blijft de tekst in zijn geheel zichtbaar
WCAG [1.4.4 Herschalen van tekst](https://nldesignsystem.nl/wcag/1.4.4)
Oordeel: voldoet.

Als je de tekstafstand van de Number Badge vergroot blijft de tekst in zijn geheel zichtbaar
WCAG [1.4.12 Tekstafstand](https://nldesignsystem.nl/wcag/1.4.12)
Oordeel: voldoet.

#### Geef de informatie uit de Number Badge ook door aan screenreaders
WCAG [1.3.1 Info en relaties](https://nldesignsystem.nl/wcag/1.3.1)
Oordeel: Context afhankelijk.

In dit acceptatiecriterium staat:
> Visueel heeft de Number Badge een betekenis die duidelijk is. Deze betekenis moet ook duidelijk zijn voor screenreadergebruikers. Het volstaat daarom meestal niet als de Number Badge alleen een cijfer toevoegt aan bijvoorbeeld een tekst 'Inbox'. De visuele layout maakt namelijk duidelijk dat het om nieuwe berichten gaat.

> Geeft dan extra tekstuele context, bijvoorbeeld met een visueel verborgen tekst:

```
<a href="/inbox">
  Inbox
  <data class="utrecht-number-badge" value="4">4</data>
  <span class="screenreader-only">nieuwe berichten</span>
</a>
```

Advies: neem de stories `Number Badge moet niet onderstreept zijn` en `Number Badge moet er in forced colors mode uitzien als een link` niet als voorbeeld, omdat deze precies doen wat wordt afgeraden, of voeg extra tekstuele context aan de stories toe.

### Opmerking over Number Badge in een Heading:
ZIe:
https://candidate-storybook-test.vercel.app/?path=/story/componenten-number-badge--font-relative

Code:
```
<h1 class="nl-heading nl-heading--level-1">
   Kopniveau <data value="1" class="nl-number-badge">1</data>
</h1>
```
VoiceOver in Safari (ik heb um op Engels staan) leest dit voor als:
`Heading level 1, 2 items Kopniveau 1`
VoiceOver leest wel alles, voor maar zegt ook 2 items erbij.
NVDA leest in FireFox:
`Heading level 1 Kopniveau 1`
Op zich geen afkeuring, maar wel iets om te onthouden en bij testen op te letten.

**Comment by rianrietveld** [comment]
@Robbert 
Ik ben het niet eens met

```
<div
  style="display: flex; flex: 1 1 0%; flex-direction: row; max-inline-size: 10em;"
>
  <span style="flex-grow: 1;">Inbox</span>
  <data value="42" class="nl-number-badge">
    <span hidden="" aria-hidden="true" class="nl-number-badge__visible-label">
      42
    </span>
    <span class="nl-number-badge__hidden-label">42 ongelezen berichten</span>
  </data>
</div>
```
2 dingen:
- Ik vind het overkill om een zichtbaar element te verbergen en alsnog toe te voegen als screen reader text.
- Waarom staat hidden="" erbij? Lijkt me gevaarlijk als een developer denkt, kom ik maar er `hidden="hidden" `van.

**Comment by Robbert** [comment]
- `hidden="hidden"` is hetzelfde als `hidden` en `hidden=""`, dus dat zou niet erg zijn.
- de `visible-label` moet onzichtbaar zijn als de CSS niet geladen kan worden, zodat de situatie dan nog steeds duidelijk is. Hier staat een comment over in de React implementatie, en daarover moet ook nog tekst komen in de algemene documentatie. https://github.com/nl-design-system/candidate/blob/main/packages/components-react/number-badge-react/src/number-badge.tsx#L23-L28
