### ISSUE TITLE
a11y: Issues toegankelijkheidstest Paragraph Candidate

### ISSUE THREAD

**Issue by MarjonBakker** [nl-design-system/candidate#373]
Algemeen: De namen van de stories zijn niet overal goed, want voor sommige stories hetzelfde.

Paragraph (zoom 200%)
Voldoet
Opmerking: `style="zoom: 400%;"` vervangen door `style="zoom: 200%;"`

Paragraph (zoom 400%)
**Voldoet niet op 1.4.10**
Opmerking: Dit is pas te testen op 1280px viewport width, in Storybook zelf is deze viewport te groot. De tekst loopt dan uit de pagina.

Paragraph (small viewport)
**Voldoet niet op 1.4.4**
Opmerking: Viewport width is 375px, waarom is voor die waarde gekozen? Voor WCAG hoef je niet op deze resolutie te testen overigens.

Paragraph (zoom 200%, small viewport)
**Voldoet niet op 1.4.4**

Paragraph (zoom 200%, small viewport)
**Voldoet niet op 1.4.10 en 1.4.12**
Opmerking: naam story aanpassen

Paragraph (zoom 200%, small viewport)
**Voldoet niet op 1.4.10 en 1.4.12**
Opmerking: naam story aanpassen

Paragraph (zoom 400%, small viewport)
**Voldoet niet op 1.4.12**
Opmerking: Deze story is niet nodig om te testen, 400% wordt niet getest op een small viewport.

**Comment by rianrietveld** [comment]
Alle issues zijn opgelost in PR #375 375
cc @MarjonBakker

**Comment by Robbert** [comment]
Er is nog een hertest nodig met "Page Titled" en "Language of the Page" in scope

**Comment by Robbert** [comment]
we hebben de test-aanpak omgegooid begin deze week, hertest heeft geen prioriteit meer
